In [ ]:
from vitabel import Vitals

In [3]:
case = Vitals()
case.add_defibrillator_recording("20260331124955_00147042_ecg.txt")

In [13]:
case.info()

,Name,Length,First Entry,Last Entry,Offset,Source,Attached Labels,Serial No
0,ecg_pads,72071,2026-03-31 12:50:06.363000,2026-03-31 12:54:54.674000,0 days 00:00:00,ZOLL - E Series,,00147042
1,ppg,10967,2026-03-31 12:54:10.089000,2026-03-31 12:54:54.106000,0 days 00:00:00,ZOLL - E Series,,00147042

Empty DataFrame
Columns: []
Index: []

In [12]:
case.plot_interactive(
    channels=[[c] for c in case.get_channel_names()],
    channel_overviews=[[[c] for c in case.get_channel_names()][0]],
    subplots_kwargs={"figsize": (14, 10)}
)

AppLayout(children=(Tab(children=(VBox(children=(HTML(value='\n                    <p>\n                    Ri…